export const GET_ACTIVE_ADS_REQUEST = 'GET_ACTIVE_ADS_REQUEST';
export const GET_ACTIVE_ADS_SUCCESS = 'GET_ACTIVE_ADS_SUCCESS';
export const GET_ACTIVE_ADS_FAILURE = 'GET_ACTIVE_ADS_FAILURE';

export const CREATE_AD_REQUEST = 'CREATE_AD_REQUEST';
export const CREATE_AD_SUCCESS = 'CREATE_AD_SUCCESS';
export const CREATE_AD_FAIL = 'CREATE_AD_FAIL';

export const UPDATE_AD_REQUEST = 'UPDATE_AD_REQUEST';
export const UPDATE_AD_SUCCESS = 'UPDATE_AD_SUCCESS';
export const UPDATE_AD_FAIL = 'UPDATE_AD_FAIL';

export const DELETE_AD = 'DELETE_AD';

export const FETCH_ADS_REQUEST = "FETCH_ADS_REQUEST";
export const FETCH_ADS_SUCCESS = "FETCH_ADS_SUCCESS";
export const FETCH_ADS_FAILURE = "FETCH_ADS_FAILURE";
export const FETCH_AD_BY_ID_SUCCESS = "FETCH_AD_BY_ID_SUCCESS";