export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'