export const SUBSCRIBE_PACKAGE_REQUEST = 'SUBSCRIBE_PACKAGE_REQUEST';
export const SUBSCRIBE_PACKAGE_SUCCESS = 'SUBSCRIBE_PACKAGE_SUCCESS';
export const SUBSCRIBE_PACKAGE_FAIL = 'SUBSCRIBE_PACKAGE_FAIL';

export const GET_ALL_PACKAGES = 'GET_ALL_PACKAGES';
export const PACKAGE_ERROR = 'PACKAGE_ERROR';

export const UPDATE_PACKAGE_REQUEST = 'UPDATE_PACKAGE_REQUEST';
export const UPDATE_PACKAGE_SUCCESS = 'UPDATE_PACKAGE_SUCCESS';
export const UPDATE_PACKAGE_FAIL = 'UPDATE_PACKAGE_FAIL';
