// storeActionTypes.js

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const STORE_REGISTER_REQUEST = 'STORE_REGISTER_REQUEST';
export const STORE_REGISTER_SUCCESS = 'STORE_REGISTER_SUCCESS';
export const STORE_REGISTER_FAIL = 'STORE_REGISTER_FAIL';

export const UPLOAD_DOCUMENT_REQUEST = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAIL = 'UPLOAD_DOCUMENT_FAIL';


export const FETCH_STORE_REQUEST = "FETCH_STORE_REQUEST";
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
export const FETCH_STORE_FAILURE = "FETCH_STORE_FAILURE";


export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAILURE = "UPDATE_STORE_FAILURE";


export const FETCH_STORES_REQUEST = "FETCH_STORES_REQUEST";
export const FETCH_STORES_SUCCESS = "FETCH_STORES_SUCCESS";
export const FETCH_STORES_FAILURE = "FETCH_STORES_FAILURE";


// storeConstants.js

export const STORE_LIST_REQUEST = 'STORE_LIST_REQUEST';
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL';



export const FETCH_STORE_PRODUCTS_REQUEST = 'FETCH_STORE_PRODUCTS_REQUEST';
export const FETCH_STORE_PRODUCTS_SUCCESS = 'FETCH_STORE_PRODUCTS_SUCCESS';
export const FETCH_STORE_PRODUCTS_FAILURE = 'FETCH_STORE_PRODUCTS_FAILURE';